CONSOLE MESSAGE: line 22: Error: Exception in success callback
Tests that when an exception is thrown in the success callback, the error callback is not invoked. Note that this test throws an exception which is not caught.

On success, you will see a series of "PASS" messages, followed by "TEST COMPLETE".


PASS successfullyParsed is true
PASS position.coords.latitude is mockLatitude
PASS position.coords.longitude is mockLongitude
PASS position.coords.accuracy is mockAccuracy

TEST COMPLETE

